services:
  - type: web
    name: money-flow
    runtime: php
    plan: free
    buildCommand: "composer install && php artisan migrate --force"
    startCommand: "php artisan serve --host 0.0.0.0 --port 10000"
    envVars:
      - key: APP_ENV
        value: local
      - key: APP_KEY
        sync: false
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: 127.0.0.1
      - key: DB_PORT
        value: 3306
      - key: DB_DATABASE
        value: custom_auth
      - key: DB_USERNAME
        value: root
      - key: DB_PASSWORD
        sync: false
